version: "3"

services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=secret
    # volume: /path/to/dir:/fluentd/log

  mysql:
    image: mysql:8
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=secret

